# Generated by Django 5.1.2 on 2024-11-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
