# Generated by Django 5.1.2 on 2024-11-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_gym_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gym",
            name="owner",
        ),
        migrations.AddField(
            model_name="gym",
            name="owners",
            field=models.ManyToManyField(related_name="gyms", to="core.gymowner"),
        ),
    ]
