# Generated by Django 5.1.2 on 2024-11-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_gym_owner_gym_owners"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="active",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
