# Generated by Django 5.1.2 on 2024-11-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_member_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
