# Generated by Django 5.1.2 on 2024-12-18 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_gymowner_is_primary_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="GymOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("primary", "Primary Owner"), ("manager", "Manager")],
                        default="manager",
                        max_length=20,
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerships",
                        to="core.gym",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gym_roles",
                        to="core.gymowner",
                    ),
                ),
            ],
            options={
                "unique_together": {("gym", "owner")},
            },
        ),
    ]
