# Generated by Django 5.1.2 on 2024-12-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_gymowner_is_primary_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="email_domain",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
