# Generated by Django 5.1.2 on 2025-01-15 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_verificationtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_gyms", models.PositiveIntegerField(default=1)),
                ("max_members", models.PositiveIntegerField(default=1000)),
                ("max_regular_products", models.PositiveIntegerField(default=10)),
                ("max_subscription_products", models.PositiveIntegerField(default=10)),
                ("max_members_per_gym", models.PositiveIntegerField(default=500)),
            ],
        ),
        migrations.AddField(
            model_name="gymowner",
            name="subscription_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gymowner",
            name="subscription_tier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.subscriptiontier",
            ),
        ),
    ]
