# Generated by Django 5.1.2 on 2025-02-13 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_subscriptiontier_gymowner_subscription_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptiontier",
            name="max_members_per_gym",
        ),
    ]
